### PR TITLE
Add Basic Support for isSuppressed & Change Support for dnd5e

### LINKED ISSUE #255: isSuppressed is not supported by Active Auras
**Describe the bug**
If an effect is suppressed, e.g. an unequipped item, still creates an aura
If an effects suppressed status changes, active auras wont care

**To Reproduce**
1. Create an Sword and add an Effect with Aura.
2. Equipped Sword -> Effect Applied -> Aura on (happy)
3. Sword unequipped -> Effect suppressed -> Aura still on (sad)

**Expected behavior**
Aura should be off because suppressed Effects grant no bonus
Active Auras should refelct changes in isSuppressed status

### PR DESCRIPTION
**Pull request by DarkByteZero**
new PR without HPCheck fix
fixes #255 
link #256

### CODE REVIEW

**Comment by DarkByteZero** [comment]
@MrPrimate 
Here is the new PR

**Comment by DarkByteZero** [comment]
ah, dont merge i made a mistake

**Comment by DarkByteZero** [comment]
ok now it should be good to go

**Comment by DarkByteZero** [comment]
okay i tested it, this should work now.

**Comment by MrPrimate** [comment]
Thanks!

**Pull request merged**
