### PR TITLE
Add IgnoreSelf option

### PR DESCRIPTION
**Pull request by wmudge**
Add an 'ignoreSelf' flag that suppresses the ActiveEffect changes of an Aura on the source actor. This is different than the 'Apply while inactive?' flag; the ignoreSelf makes it clear that the aura is either active or inactive to others without deleting the effect on the bearer.

This is appropriate for debuffs and for times when the effect should not affect the bearer. (In my set up, the paladin's Aura of Protection was automatically applied the character via the system - not sure why, but the character was imported from DNDBeyond. Adding an aura with the same effect doubled the bonus, so I added this flag to avoid the duplication.)

### CODE REVIEW

**Comment by kandashi** [comment]
The "apply while inactive" is intended for this purpos, keep the effect inactive on the aura token and it will still apply to tokens around it. I'd you have hard coded bonuses on the actor I should suggest removing them rather than chasing the module to match your use case.

**Comment by wmudge** [comment]
Inactive means not active, so why would the aura still affect others? Either the effect is active and affects others, or it’s completely inactive.

**Comment by wmudge** [comment]
Latest push handles missing initial flags for the ActiveEffect (ran into this with adding AA to. a Combat Utility Belt condition)

**Comment by kandashi** [comment]
So looking over this, its a bit out of my depth. From what I can tell you prevent the aura from actually applying its effect to the actor that owns the item, even when it is active correct?

**Comment by kandashi** [comment]
Thank you for the time to make this change. Ive merged it into the main branch and removed the "apply while inactive" as this replaces that functionality

**Pull request merged**
