### PR TITLE
v10 compatibility

### PR DESCRIPTION
**Pull request by kaelad02**
Make AA compatible with v10.

- update the manifest file
- adjust to the Data Model changes by either removing `.data` or changing some cases to `.document`
- migrate the compendiums

### CODE REVIEW

**Comment by kaelad02** [comment]
It still needs #240 to be compatible with v10. I tested with that fix in but I didn't include it in this PR since you've already got that other PR.

**Comment by CaosFR** [comment]
@kandashi Hi, any news for the merge ?

**Comment by MrPrimate** [comment]
@CaosFR if you need to be able to run Active-Auras in v10, you can use the following manifest links to install the modules, these include the v10 fixes plus a couple of other PR's that folks have logged here. 

- Active Auras: https://github.com/MrPrimate/Active-Auras/releases/download/v0.4.14/module.json
- Active Token Effects/Lighting: https://github.com/MrPrimate/Active-Token-Lighting/releases/download/v0.4.02/module.json

**Comment by CaosFR** [comment]
@MrPrimate Amazing ! Thanks.

**Comment by kaelad02** [comment]
Do we need this anymore since #246 was merged?

**Comment by MrPrimate** [comment]
> Do we need this anymore since #246 was merged?

No, all your changes were merged into my PR as it's base

**Pull request closed without merging**
